# Generated by Django 4.0 on 2022-11-26 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_course_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=datetime.datetime(2022, 11, 26, 8, 25, 17, 604527, tzinfo=utc), upload_to='Coursepic/', verbose_name='Kurs rasmi'),
            preserve_default=False,
        ),
    ]
